version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: wb_redis
    restart: always

  db:
    image: postgres:15-alpine
    container_name: wb_postgres
    restart: always
    environment:
      - POSTGRES_USER=wb_user
      - POSTGRES_PASSWORD=wb_secret_password
      - POSTGRES_DB=wb_monitor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # ВАЖНО: Указываем правильного юзера для проверки
      test: ["CMD-SHELL", "pg_isready -U wb_user -d wb_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: wb_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://wb_user:wb_secret_password@db:5432/wb_monitor
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - HEADLESS=True
      - BOT_TOKEN=${BOT_TOKEN}
      - AI_API_KEY=${AI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./backend
    container_name: wb_worker
    environment:
      - C_FORCE_ROOT=1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://wb_user:wb_secret_password@db:5432/wb_monitor
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - HEADLESS=True
      - AI_API_KEY=${AI_API_KEY}
    command: celery -A celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  beat:
    build: ./backend
    container_name: wb_beat
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://wb_user:wb_secret_password@db:5432/wb_monitor
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis

volumes:
  postgres_data: